"""Integration tests for GET /api/agent/tasks/{task_id}/export.md.

The markdown export is the portable middle ground between the styled
PDF report and the raw JSON dump: it must carry the question, final
answer, intelligence score, sources, and the post-pipeline reports
(steelman, assumptions, temporal profile, source integrity, dissent)
in a single .md attachment, and it must share the same ownership and
readiness guards as the other task exports (404 for foreign/missing
tasks, 400 while the task has no final answer).
"""

from __future__ import annotations

import json
import uuid

import pytest

from arena.core.auth import create_access_token
from arena.core.report_generator import generate_report_markdown
from arena.db_models import AgentTask, UserTier


def _headers(user):
    return {"Authorization": f"Bearer {create_access_token(user.id, user.email)}"}


def _reports() -> dict:
    return {
        "source_integrity": {
            "source_count": 3,
            "overall_source_integrity": 88,
            "integrity_label": "high",
            "summary": "Sources agree on the core claims.",
            "claims": [{"claim": "c1", "agreement_confidence": 90}],
            "contradictions": [],
        },
        "assumptions": {
            "assumption_count": 2,
            "assumptions": [
                {"assumption": "a1", "criticality": "high", "flag": True},
                {"assumption": "a2", "criticality": "low", "flag": False},
            ],
        },
        "dissent_report": {
            "positions": [{"label": "for", "count": 3}],
            "minority_view_summary": "One reviewer disagrees on pacing.",
        },
        "temporal_profile": {
            "decay_class": "durable",
            "half_life": "2-5 years",
            "recheck_by": None,
            "time_sensitive_claims": [],
        },
        "steelman": {
            "opposing_position": "The opposite view",
            "key_arguments": ["arg1"],
            "strongest_evidence": "evidence",
            "concession": "concede",
        },
    }


def _seed_task(
    db_session,
    *,
    user_id: int,
    task_id: str | None = None,
    reports: dict | None = None,
) -> AgentTask:
    row = AgentTask(
        user_id=user_id,
        task_id=task_id or str(uuid.uuid4()),
        title="Markdown export",
        task_text="Do the reports export to markdown?",
        final_answer="Yes, they export cleanly.",
        final_score=82,
        final_confidence=0.8,
        sources_used=json.dumps(["source-a", "source-b"]),
    )
    if reports:
        row.source_integrity = reports["source_integrity"]
        row.assumptions = reports["assumptions"]
        row.dissent_report = reports["dissent_report"]
        row.temporal_profile = reports["temporal_profile"]
        row.steelman = reports["steelman"]
        row.intelligence_score = json.dumps(
            {
                "total_score": 82,
                "score_label": "strong",
                "one_line_verdict": "A solid, well-sourced answer.",
                "research_depth": {"score": 20},
                "logical_soundness": {"score": 21},
                "consensus_level": {"score": 20},
                "answer_durability": {"score": 21},
            }
        )
    db_session.add(row)
    db_session.flush()
    return row


@pytest.mark.asyncio
async def test_export_markdown_includes_report_sections(
    app_client, make_user, db_session
):
    user = make_user(email="md-export@test.com", tier=UserTier.PRO)
    row = _seed_task(
        db_session, user_id=user.id, task_id="md-export-1", reports=_reports()
    )
    db_session.commit()

    res = await app_client.get(
        f"/api/agent/tasks/{row.task_id}/export.md",
        headers=_headers(user),
    )
    assert res.status_code == 200
    assert res.headers["content-type"].startswith("text/markdown")
    assert f"arena-report-{row.task_id[:8]}.md" in res.headers["content-disposition"]

    body = res.text
    assert "# Do the reports export to markdown?" in body
    assert "## Answer" in body
    assert "Yes, they export cleanly." in body
    assert "**82/100**" in body
    assert "1. source-a" in body
    assert "2. source-b" in body
    assert "## Steelman" in body
    assert "The opposite view" in body
    assert "## Key Assumptions" in body
    assert "criticality: high" in body
    assert "## Source Integrity" in body
    assert "Sources agree on the core claims." in body
    assert "## Dissent" in body
    assert "One reviewer disagrees on pacing." in body
    assert "## Temporal Profile" in body
    assert "**Decay class:** Durable" in body
    assert "_Generated by Arena ·" in body


@pytest.mark.asyncio
async def test_export_markdown_scopes_to_owner(
    app_client, make_user, db_session
):
    owner = make_user(email="md-owner@test.com", tier=UserTier.PRO)
    other = make_user(email="md-other@test.com", tier=UserTier.PRO)
    row = _seed_task(db_session, user_id=owner.id, task_id="md-owner-1")
    db_session.commit()

    res = await app_client.get(
        f"/api/agent/tasks/{row.task_id}/export.md",
        headers=_headers(other),
    )
    assert res.status_code == 404

    missing = await app_client.get(
        "/api/agent/tasks/does-not-exist/export.md",
        headers=_headers(owner),
    )
    assert missing.status_code == 404


@pytest.mark.asyncio
async def test_export_markdown_requires_final_answer(
    app_client, make_user, db_session
):
    user = make_user(email="md-empty@test.com", tier=UserTier.PRO)
    row = _seed_task(db_session, user_id=user.id, task_id="md-empty-1")
    row.final_answer = None
    db_session.commit()

    res = await app_client.get(
        f"/api/agent/tasks/{row.task_id}/export.md",
        headers=_headers(user),
    )
    assert res.status_code == 400


def test_generate_report_markdown_empty_answer_placeholder():
    row = AgentTask(
        user_id=1,
        task_id="unit-md-1",
        task_text="Unit question",
        final_answer=None,
    )
    body = generate_report_markdown(row, {})
    assert "# Unit question" in body
    assert "_No answer recorded for this task._" in body
    assert "_Generated by Arena ·" in body
